<?php

/*
 * Branding configs for your application
 */
return [
    'login' => [
        'page_title' => 'تسجيل الدخول',
        'headline' => 'تسجيل الدخول',
        'subheadline' => 'قم بتسجيل الدخول إلى حسابك أدناه',
        'show_subheadline' => true,
        'email_address' => 'عنوان البريد الإلكتروني',
        'password' => 'كلمة المرور',
        'edit' => 'تعديل',
        'button' => 'متابعة',
        'forget_password' => 'نسيت كلمة المرور؟',
        'dont_have_an_account' => 'ليس لديك حساب؟',
        'sign_up' => 'اشترك الآن',
        'social_auth_authenticated_message' => 'لقد تم التحقق من هويتك عبر social_providers_list. يرجى تسجيل الدخول إلى تلك الشبكة أدناه.',
        'change_email' => 'تغيير البريد الإلكتروني',
    ],
    'register' => [
        'page_title' => 'Sign up',
        'headline' => 'Sign up',
        'subheadline' => 'Register for your free account below.',
        'show_subheadline' => false,
        'name' => 'Name',
        'email_address' => 'Email Address',
        'password' => 'Password',
        'password_confirmation' => 'Confirm Password',
        'already_have_an_account' => 'Already have an account?',
        'sign_in' => 'Sign in',
        'button' => 'Continue',
    ],
    'verify' => [
        'page_title' => 'تحقق من حسابك',
        'headline' => 'تحقق من عنوان بريدك الإلكتروني',
        'subheadline' => 'قبل المتابعة، يجب عليك التحقق من بريدك الإلكتروني.',
        'show_subheadline' => false,
        'description' => 'يرجى التحقق من بريدك الإلكتروني للحصول على رابط التحقق قبل المتابعة. إذا لم تستلم البريد الإلكتروني،',
        'new_request_link' => 'انقر هنا لطلب رابط آخر',
        'new_link_sent' => 'تم إرسال رابط جديد إلى عنوان بريدك الإلكتروني.',
        'or' => 'أو',
        'logout' => 'انقر هنا لتسجيل الخروج',
    ],
    'passwordConfirm' => [
        'page_title' => 'Confirm Your Password',
        'headline' => 'Confirm Password',
        'subheadline' => 'Be sure to confirm your password below',
        'show_subheadline' => false,
        'password' => 'Password',
        'button' => 'Confirm password',
    ],
    'passwordResetRequest' => [
        'page_title' => 'Request a Password Reset',
        'headline' => 'Reset password',
        'subheadline' => 'Enter your email below to reset your password',
        'show_subheadline' => false,
        'email' => 'Email Address',
        'button' => 'Send password reset link',
        'or' => 'or',
        'return_to_login' => 'return to login',
    ],
    'passwordReset' => [
        'page_title' => 'Reset Your Password',
        'headline' => 'Reset Password',
        'subheadline' => 'Reset your password below',
        'show_subheadline' => false,
        'email' => 'Email Address',
        'password' => 'Password',
        'password_confirm' => 'Confirm Password',
        'button' => 'Reset Password',
    ],
    'twoFactorChallenge' => [
        'page_title' => 'Two Factor Challenge',
        'headline_auth' => 'Authentication Code',
        'subheadline_auth' => 'Enter the authentication code provided by your authenticator application.',
        'show_subheadline_auth' => false,
        'headline_recovery' => 'Recovery Code',
        'subheadline_recovery' => 'Please confirm access to your account by entering one of your emergency recovery codes.',
        'show_subheadline_recovery' => false,
    ],

];
